'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'pt' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    'nav.services': 'Serviços',
    'nav.portfolio': 'Portfólio',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'nav.portal': 'Portal do Cliente',
    'nav.quote': 'Orçamento',
    'footer.company': 'Empresa',
    'footer.services': 'Serviços',
    'footer.client': 'Cliente',
    'footer.legal': 'Legal',
    'footer.aboutUs': 'Sobre Nós',
    'footer.fdm': 'Impressão FDM',
    'footer.resin': 'Impressão de Resina',
    'footer.parts': 'Peças Industriais',
    'footer.customDesign': 'Design Personalizado',
    'footer.tracking': 'Rastreamento',
    'footer.catalog': 'Catálogo',
    'footer.privacy': 'Privacidade',
    'footer.terms': 'Termos',
    'footer.desc': 'Componentes impressos em 3D de precisão para aplicações industriais e criativas. Criados com curvas de Bézier, entregues com cuidado.',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.builtWith': 'Criado com',
    'footer.precision': 'precisão',
    'footer.using': 'usando',
    'ticker.title': 'LÍDERES DE MERCADO QUE CONFIAM NA BÉZIER LAB',
    'hero.badge': 'Catálogo de Produtos 3D Exclusivos',
    'hero.title.1': 'Premium B2B & B2C',
    'hero.title.2': 'manufatura aditiva',
    'hero.title.3': 'produtos sob demanda.',
    'hero.desc': 'Descubra brindes corporativos sofisticados e desk drops estéticos. Encomende diretamente de nosso catálogo interativo com branding personalizado e entrega expressa.',
    'hero.cta.primary': 'Iniciar seu Projeto',
    'hero.cta.secondary': 'Ver Portfólio',
    'hero.trust.1': 'Qualidade ISO 9001',
    'hero.trust.2': 'Urgente em 24h Disponível',
    'hero.trust.3': 'Consultoria Gratuita',
    'hero.badge.parts': 'Peças entregues',
    'hero.badge.time': 'Tempo de entrega',
    'hero.scene': 'Cena 3D interativa',
    'hero.scroll.p1.line1': 'Curadoria',
    'hero.scroll.p1.line2': 'Exclusiva.',
    'hero.scroll.p1.title': 'Produtos Exclusivos',
    'hero.scroll.p1.desc': 'Navegue pelo nosso catálogo curado de brindes corporativos e drops de mesa de alto padrão.',
    'hero.scroll.p2.line1': 'Personalização',
    'hero.scroll.p2.line2': '3D Ativa.',
    'hero.scroll.p2.title': 'Personalização 3D',
    'hero.scroll.p2.desc': 'Configure cores de acabamento, insira o logotipo da sua empresa e visualize em tempo real antes de encomendar.',
    'hero.scroll.p3.line1': 'Performance',
    'hero.scroll.p3.line2': 'de Materiais.',
    'hero.scroll.p3.title': 'Materiais de Performance',
    'hero.scroll.p3.desc': 'Peças fabricadas com fibra de carbono de grau aeroespacial, TPU emborrachado e resina de ultra resolução.',
    'hero.scroll.cta.title': 'Pronto para fabricar as suas ideias?',
    'hero.scroll.cta.desc': 'Envie seus arquivos CAD e receba uma análise de manufatura e orçamento em tempo recorde.',
    'how.title': 'Como Funciona',
    'how.desc': 'Do catálogo interativo para a sua mesa em quatro passos simples.',
    'how.step1.num': '01',
    'how.step1.title': 'Escolha no Catálogo',
    'how.step1.desc': 'Explore nossos designs selecionados para brindes corporativos (B2B) e desk drops estéticos (B2C).',
    'how.step2.num': '02',
    'how.step2.title': 'Personalize em 3D',
    'how.step2.desc': 'Adicione o logotipo da sua empresa, escolha cores premium e selecione materiais de engenharia avançados.',
    'how.step3.num': '03',
    'how.step3.title': 'Manufatura de Elite',
    'how.step3.desc': 'Seu pedido personalizado é enviado para nossa fazenda de impressão de alta tolerância, utilizando fibra de carbono, TPU e resina.',
    'how.step4.num': '04',
    'how.step4.title': 'Entrega Direta',
    'how.step4.desc': 'Entregue em lote no seu escritório ou enviado individualmente direto para a mesa de cada destinatário.',
    'coverage.title': 'Logística Bézier Express',
    'coverage.desc': 'Envio e distribuição expressa para todo o território nacional direto de nossa matriz em São Paulo.',
    'coverage.stat.1': 'Todo o Brasil',
    'coverage.stat.1.desc': 'Cobertura completa para todas as capitais e regiões metropolitanas.',
    'coverage.stat.2': 'Expresso 24-48h',
    'coverage.stat.2.desc': 'Opções de frete prioritário aéreo e rodoviário para peças urgentes.',
    'coverage.stat.3': 'Seguro Total',
    'coverage.stat.3.desc': 'Todas as remessas são embaladas sob medida com seguro integral contra avarias.',
    'stats.parts': 'Peças entregues',
    'stats.quality': 'Taxa de qualidade',
    'stats.turnaround': 'Entrega média',
    'stats.clients': 'Clientes satisfeitos',
    'features.badge': 'Serviços',
    'features.title': 'O que entregamos',
    'features.desc': 'Serviços de impressão 3D de ponta a ponta desenvolvidos para aplicações exigentes.',
    'features.f1.title': 'Precisão Industrial',
    'features.f1.desc': 'Tolerâncias de até ±0.1mm para componentes críticos usando tecnologias FDM, resina e SLS.',
    'features.f2.title': 'Domínio de Materiais',
    'features.f2.desc': 'Desde protótipos em PLA a peças de engenharia em PETG, compostos de titânio e TPU flexível.',
    'features.f3.title': 'Qualidade Garantida',
    'features.f3.desc': 'Cada peça passa por uma verificação rigorosa antes do envio. Sua satisfação é nossa prioridade.',
    'features.f4.title': 'Produção Rápida',
    'features.f4.desc': 'Ciclos de produção de 24h a 72h para a maioria das peças. Pedidos de emergência disponíveis.',
    'features.f5.title': 'Design Personalizado',
    'features.f5.desc': 'Tem uma ideia? Nosso time de design converte esboços, arquivos Figma ou CAD em arquivos prontos.',
    'features.f6.title': 'Envio Global',
    'features.f6.desc': 'Embalado com precisão e enviado para todo o mundo. Rastreie em tempo real pelo portal.',
    'portfolio.badge': 'Portfólio',
    'portfolio.title': 'Projetos recentes',
    'portfolio.viewAll': 'Ver todos',
    'cat.industrial': 'Industrial',
    'cat.healthcare': 'Saúde',
    'cat.design': 'Design',
    'cat.aerospace': 'Aeroespacial',
    'cat.medical': 'Médico',
    'test.q1': 'A precisão é extraordinária. As peças encaixam-se perfeitamente na primeira tentativa — retrabalho zero.',
    'test.q2': 'Nosso cronograma de protótipos passou de 3 semanas para 3 dias. Um estúdio revolucionário.',
    'test.q3': 'O portal do cliente torna o rastreamento de pedidos muito fácil. Uma experiência profissional do início ao fim.',
    'testimonials.badge': 'Avaliações',
    'testimonials.title': 'Recomendado por quem constrói',
    'cta.badge': 'Aberto para projetos',
    'cta.title.1': 'Pronto para dar vida',
    'cta.title.2': 'ao seu projeto?',
    'cta.desc': 'Compartilhe seus arquivos CAD ou esboços e enviaremos um orçamento gratuito em até 24 horas. Sem compromisso.',
    'cta.button.primary': 'Solicitar Orçamento Grátis',
    'cta.button.secondary': 'Portal do Cliente',
    'admin.section.main': 'Principal',
    'admin.section.manage': 'Gerenciar',
    'admin.section.system': 'Sistema',
    'admin.nav.dashboard': 'Painel',
    'admin.nav.inventory': 'Inventário',
    'admin.nav.products': 'Produtos',
    'admin.nav.orders': 'Pedidos',
    'admin.nav.clients': 'Clientes',
    'admin.nav.settings': 'Configurações',
    'admin.nav.signout': 'Sair',
    'admin.dashboard.greeting.morning': 'Bom dia',
    'admin.dashboard.greeting.afternoon': 'Boa tarde',
    'admin.dashboard.greeting.evening': 'Boa noite',
    'admin.dashboard.recentOrders': 'Pedidos Recentes',
    'admin.dashboard.viewAll': 'Ver todos',
    'admin.dashboard.totalProducts': 'Produtos Publicados',
    'admin.dashboard.totalOrders': 'Total de Pedidos',
    'admin.dashboard.totalClients': 'Clientes',
    'admin.dashboard.pendingOrders': 'Pedidos Pendentes',
    'admin.dashboard.emptyOrders': 'Nenhum pedido ainda. Os produtos precisam ser publicados para os clientes fazerem pedidos.',
    'admin.dashboard.orderNumber': 'Pedido #',
    'admin.dashboard.client': 'Cliente',
    'admin.dashboard.status': 'Status',
    'admin.dashboard.amount': 'Valor',
    'admin.dashboard.date': 'Data',
    'admin.inventory.management': 'Gerenciamento',
    'admin.inventory.title': 'Inventário',
    'admin.inventory.addProduct': 'Adicionar Produto',
    'admin.inventory.search': 'Buscar produtos...',
    'admin.inventory.filter': 'Filtrar',
    'admin.inventory.total': 'Total',
    'admin.inventory.published': 'Publicados',
    'admin.inventory.draft': 'Rascunhos',
    'admin.inventory.outOfStock': 'Esgotados',
    'admin.inventory.product': 'Produto',
    'admin.inventory.category': 'Categoria',
    'admin.inventory.price': 'Preço',
    'admin.inventory.stock': 'Estoque',
    'admin.inventory.status': 'Status',
    'admin.inventory.actions': 'Ações',
    'admin.inventory.empty': 'Nenhum produto encontrado.',
    'admin.inventory.deleteTitle': 'Excluir Produto',
    'admin.inventory.deleteConfirm': 'Tem certeza de que deseja excluir este produto? Esta ação não pode ser desfeita.',
    'admin.inventory.cancel': 'Cancelar',
    'admin.inventory.delete': 'Excluir',
    'admin.inventory.count': 'Mostrando {0} de {1} produtos',
    'admin.inventory.page': 'Página {0} de {1}',
    'ds.version': 'v0.1.0 — Tecnologia Modo Escuro',
    'ds.title': 'Bézier UI',
    'ds.desc': 'O sistema de design oficial do Bézier Lab. Construído com precisão, projetado para escala — cada token, componente e padrão documentado aqui.',
    'ds.stats.components': 'Componentes',
    'ds.stats.tokens': 'Design Tokens',
    'ds.stats.categories': 'Categorias de Tokens',
    'ds.stats.a11y': 'Acessibilidade',
    'ds.explore': 'Explore o Sistema',
    'ds.section.guidelines': 'Diretrizes',
    'ds.section.guidelines.desc': 'Princípios de marca, linguagem de movimento e padrões de acessibilidade.',
    'ds.section.tokens': 'Design Tokens',
    'ds.section.tokens.desc': 'Os valores atômicos por trás de cada decisão de design — cores, espaçamento, tipografia.',
    'ds.section.components': 'Componentes',
    'ds.section.components.desc': 'Uma biblioteca com mais de 12 componentes React prontos para produção construídos com Radix UI.',
    'ds.section.playground': 'Playground',
    'ds.section.playground.desc': 'Teste e configure interativamente todas as variantes de componentes em tempo real.',
    'ds.colors.title': 'Tokens de Cores',
    'ds.colors.viewAll': 'Ver todos',
    'ds.typography.title': 'Tipografia — Inter',
    'ds.components.title': 'Componentes',
    'ds.components.browseAll': 'Navegar por todos',
    'admin.section.shortcuts': 'Atalhos',
    'admin.nav.storefront': 'Ir para a Loja',
    'admin.nav.catalog': 'Ver Catálogo',
    'admin.nav.ds': 'Design System',
  },
  en: {
    'nav.services': 'Services',
    'nav.portfolio': 'Portfolio',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.portal': 'Client Portal',
    'nav.quote': 'Get a Quote',
    'footer.company': 'Company',
    'footer.services': 'Services',
    'footer.client': 'Client',
    'footer.legal': 'Legal',
    'footer.aboutUs': 'About Us',
    'footer.fdm': 'FDM Printing',
    'footer.resin': 'Resin Printing',
    'footer.parts': 'Industrial Parts',
    'footer.customDesign': 'Custom Design',
    'footer.tracking': 'Order Tracking',
    'footer.catalog': 'Product Catalog',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.desc': 'Precision-engineered 3D printing for industrial and creative applications. Built with Bézier curves, delivered with care.',
    'footer.rights': 'All rights reserved.',
    'footer.builtWith': 'Built with',
    'footer.precision': 'precision',
    'footer.using': 'using',
    'ticker.title': 'TRUSTED BY LEADING HARDWARE & ENGINEERING COMPANIES',
    'hero.badge': 'Curated 3D Product Marketplace',
    'hero.title.1': 'Premium B2B & B2C',
    'hero.title.2': 'additive manufacturing',
    'hero.title.3': 'products on demand.',
    'hero.desc': 'Discover high-end corporate gifts and aesthetic desk drops. Order directly from our interactive catalog with custom branding and express delivery.',
    'hero.cta.primary': 'Start Your Project',
    'hero.cta.secondary': 'View Portfolio',
    'hero.trust.1': 'ISO 9001 Quality',
    'hero.trust.2': '24h Rush Available',
    'hero.trust.3': 'Free Consultation',
    'hero.badge.parts': 'Parts delivered',
    'hero.badge.time': 'Turnaround time',
    'hero.scene': 'Interactive 3D scene',
    'hero.scroll.p1.line1': 'Curated',
    'hero.scroll.p1.line2': 'Collection.',
    'hero.scroll.p1.title': 'Exclusive Products',
    'hero.scroll.p1.desc': 'Browse our curated catalog of high-end corporate gifts and premium desk drops.',
    'hero.scroll.p2.line1': 'Active',
    'hero.scroll.p2.line2': '3D Personalization.',
    'hero.scroll.p2.title': '3D Personalization',
    'hero.scroll.p2.desc': 'Configure finishing colors, insert your company logo, and preview in real-time before ordering.',
    'hero.scroll.p3.line1': 'Material',
    'hero.scroll.p3.line2': 'Performance.',
    'hero.scroll.p3.title': 'Material Performance',
    'hero.scroll.p3.desc': 'Parts fabricated with aerospace-grade carbon fiber, rubberized TPU, and ultra-resolution resin.',
    'hero.scroll.cta.title': 'Ready to manufacture your ideas?',
    'hero.scroll.cta.desc': 'Submit your CAD designs for an engineering audit and get a custom quote in under 24 hours.',
    'how.title': 'How It Works',
    'how.desc': 'From interactive catalog to your desk in four simple steps.',
    'how.step1.num': '01',
    'how.step1.title': 'Browse Catalog',
    'how.step1.desc': 'Explore our curated designs for corporate gifts (B2B) and aesthetic desk drops (B2C).',
    'how.step2.num': '02',
    'how.step2.title': 'Personalize 3D',
    'how.step2.desc': 'Add your company logo, select premium colors, and choose high-end engineering materials.',
    'how.step3.num': '03',
    'how.step3.title': 'Automated Print',
    'how.step3.desc': 'Your personalized order is routed to our high-tolerance print farm using carbon fiber, TPU, and resin.',
    'how.step4.num': '04',
    'how.step4.title': 'Direct Desk Drop',
    'how.step4.desc': 'Delivered in bulk to your office or shipped individually directly to each recipient\'s desk.',
    'coverage.title': 'Bézier Express Logistics',
    'coverage.desc': 'Express shipping and logistics nationwide directly from our primary facility in São Paulo.',
    'coverage.stat.1': 'Brazil-Wide',
    'coverage.stat.1.desc': 'Full shipping coverage across all capitals and major industrial hubs.',
    'coverage.stat.2': '24-48h Priority',
    'coverage.stat.2.desc': 'Priority air freight and express courier routes for mission-critical parts.',
    'coverage.stat.3': '100% Insured',
    'coverage.stat.3.desc': 'All components are custom-crated and fully insured during transport.',
    'stats.parts': 'Parts delivered',
    'stats.quality': 'Quality pass rate',
    'stats.turnaround': 'Avg. turnaround',
    'stats.clients': 'Happy clients',
    'features.badge': 'Services',
    'features.title': 'What we deliver',
    'features.desc': 'End-to-end 3D printing services engineered for demanding applications.',
    'features.f1.title': 'Industrial Precision',
    'features.f1.desc': 'Tolerances as tight as ±0.1mm for mission-critical components using FDM, resin, and SLS technologies.',
    'features.f2.title': 'Material Mastery',
    'features.f2.desc': 'From PLA prototypes to PETG engineering-grade parts, titanium-infused composites, and flexible TPU.',
    'features.f3.title': 'Quality Guaranteed',
    'features.f3.desc': 'Every part passes a rigorous quality check before shipping. Your satisfaction is non-negotiable.',
    'features.f4.title': 'Rapid Turnaround',
    'features.f4.desc': '24-72 hour production cycles for most parts. Rush orders available for time-critical projects.',
    'features.f5.title': 'Custom Design',
    'features.f5.desc': 'Have an idea? Our design team converts sketches, Figma files, or CAD specs into print-ready files.',
    'features.f6.title': 'Global Shipping',
    'features.f6.desc': 'Precision-packaged and shipped worldwide. Track your order in real-time through the client portal.',
    'portfolio.badge': 'Portfolio',
    'portfolio.title': 'Recent projects',
    'portfolio.viewAll': 'View all',
    'cat.industrial': 'Industrial',
    'cat.healthcare': 'Healthcare',
    'cat.design': 'Design',
    'cat.aerospace': 'Aerospace',
    'cat.medical': 'Medical',
    'test.q1': 'The precision is extraordinary. Parts fit perfectly on the first try — zero rework.',
    'test.q2': 'Our prototype timeline went from 3 weeks to 3 days. Game-changing studio.',
    'test.q3': 'The client portal makes order tracking effortless. Professional experience throughout.',
    'testimonials.badge': 'Client reviews',
    'testimonials.title': 'Trusted by builders',
    'cta.badge': 'Open for projects',
    'cta.title.1': 'Ready to bring your',
    'cta.title.2': 'design to life?',
    'cta.desc': 'Share your CAD files or sketches and we\'ll provide a free quote within 24 hours. No commitment required.',
    'cta.button.primary': 'Get a Free Quote',
    'cta.button.secondary': 'Client Portal',
    'admin.section.main': 'Main',
    'admin.section.manage': 'Manage',
    'admin.section.system': 'System',
    'admin.nav.dashboard': 'Dashboard',
    'admin.nav.inventory': 'Inventory',
    'admin.nav.products': 'Products',
    'admin.nav.orders': 'Orders',
    'admin.nav.clients': 'Clients',
    'admin.nav.settings': 'Settings',
    'admin.nav.signout': 'Sign out',
    'admin.dashboard.greeting.morning': 'Good morning',
    'admin.dashboard.greeting.afternoon': 'Good afternoon',
    'admin.dashboard.greeting.evening': 'Good evening',
    'admin.dashboard.recentOrders': 'Recent Orders',
    'admin.dashboard.viewAll': 'View all',
    'admin.dashboard.totalProducts': 'Published Products',
    'admin.dashboard.totalOrders': 'Total Orders',
    'admin.dashboard.totalClients': 'Clients',
    'admin.dashboard.pendingOrders': 'Pending Orders',
    'admin.dashboard.emptyOrders': 'No orders yet. Products need to be posted for clients to order.',
    'admin.dashboard.orderNumber': 'Order #',
    'admin.dashboard.client': 'Client',
    'admin.dashboard.status': 'Status',
    'admin.dashboard.amount': 'Amount',
    'admin.dashboard.date': 'Date',
    'admin.inventory.management': 'Management',
    'admin.inventory.title': 'Inventory',
    'admin.inventory.addProduct': 'Add Product',
    'admin.inventory.search': 'Search products...',
    'admin.inventory.filter': 'Filter',
    'admin.inventory.total': 'Total',
    'admin.inventory.published': 'Published',
    'admin.inventory.draft': 'Draft',
    'admin.inventory.outOfStock': 'Out of stock',
    'admin.inventory.product': 'Product',
    'admin.inventory.category': 'Category',
    'admin.inventory.price': 'Price',
    'admin.inventory.stock': 'Stock',
    'admin.inventory.status': 'Status',
    'admin.inventory.actions': 'Actions',
    'admin.inventory.empty': 'No products found.',
    'admin.inventory.deleteTitle': 'Delete Product',
    'admin.inventory.deleteConfirm': 'Are you sure you want to delete this product? This action cannot be undone.',
    'admin.inventory.cancel': 'Cancel',
    'admin.inventory.delete': 'Delete',
    'admin.inventory.count': 'Showing {0} of {1} products',
    'admin.inventory.page': 'Page {0} of {1}',
    'ds.version': 'v0.1.0 — Dark Mode Tech',
    'ds.title': 'Bézier UI',
    'ds.desc': 'The official design system for Bézier Lab. Built with precision, engineered for scale — every token, component, and pattern documented here.',
    'ds.stats.components': 'Components',
    'ds.stats.tokens': 'Design Tokens',
    'ds.stats.categories': 'Token Categories',
    'ds.stats.a11y': 'Accessibility',
    'ds.explore': 'Explore the System',
    'ds.section.guidelines': 'Guidelines',
    'ds.section.guidelines.desc': 'Brand principles, motion language, and accessibility standards.',
    'ds.section.tokens': 'Design Tokens',
    'ds.section.tokens.desc': 'The atomic values behind every design decision — colors, spacing, typography.',
    'ds.section.components': 'Components',
    'ds.section.components.desc': 'A library of 12+ production-ready React components built with Radix UI.',
    'ds.section.playground': 'Playground',
    'ds.section.playground.desc': 'Interactively test and configure all component variants in real-time.',
    'ds.colors.title': 'Color Tokens',
    'ds.colors.viewAll': 'View all',
    'ds.typography.title': 'Typography — Inter',
    'ds.components.title': 'Components',
    'ds.components.browseAll': 'Browse all',
    'admin.section.shortcuts': 'Shortcuts',
    'admin.nav.storefront': 'Go to Storefront',
    'admin.nav.catalog': 'View Catalog',
    'admin.nav.ds': 'Design System',
  }
}

const LanguageContext = createContext<LanguageContextType | null>(null)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('pt')

  useEffect(() => {
    const stored = localStorage.getItem('bezier-lang') as Language
    if (stored === 'pt' || stored === 'en') {
      setLanguageState(stored)
      document.documentElement.lang = stored === 'pt' ? 'pt-BR' : 'en'
    } else {
      const locale = navigator.language.slice(0, 2)
      const initial: Language = locale === 'pt' ? 'pt' : 'en'
      setLanguageState(initial)
      document.documentElement.lang = initial === 'pt' ? 'pt-BR' : 'en'
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('bezier-lang', lang)
    document.documentElement.lang = lang === 'pt' ? 'pt-BR' : 'en'
  }

  const t = (key: string) => {
    return translations[language]?.[key] || translations['pt']?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
